spring:
  datasource:
   url: jdbc:h2:mem:testdb
   username: sa
   password: 
   driver-class-name: org.h2.Driver
  jpa:
   properties:
    hibernate:
     show_sql: true
   defer-datasource-initialization: true
mail:
    host: smtp.gmail.com
    port: 587
    username: avion5693@gmail.com
    password: avinash9768145640
    properties:
     mail:
     smtp:
     starttls:
     enable: true
     auth: true